POST http://localhost:5000/api/auth/refresh-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vYmluNDMyMSIsImlhdCI6MTcwMzUwMDk1Nn0.gp5J_N7izqFT74zJED2Ld2wPwoBz-7_NkZG2UThk-z0"
}