POST http://localhost:5000/api/auth/refresh-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vYmluNDMyMSIsImlhdCI6MTcwMzUwMDk1Nn0.gp5J_N7izqFT74zJED2Ld2wPwoBz-7_NkZG2UThk-z0"
}

###


GET http://localhost:4000/api/reviews/averageRating/658aa925fd3f251997ad8bae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vYmluNDMyMSIsImlhdCI6MTcwMzYwNzk2OSwiZXhwIjoxNzAzNjA4ODY5fQ.VrHyYdywaJAFY7pliuVTu404R8cv1rRNliLzzj71-vQ

###

POST http://localhost:4000/api/reviews/createReview
Content-Type: application/json

{
  "userId": "6587db8fd4b4cd2846494c0d",
  "productId":"658aa925fd3f251997ad8bae",
  "rating": 3, 
  "comment": "Great product!"
}
###

GET http://localhost:4000/api/products/getProductsByCategory/656c293bfef1304065688066
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNraGFuNzEyIiwiaWF0IjoxNzAzNzc3OTQwLCJleHAiOjE3MDM3ODE1NDB9.u0S0GFz3IDL9C1RJscwG7uZEEvgcJxxZXiJY-QldfI8

###
POST http://localhost:4000/api/cart/addToCart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNraGFuNzEyIiwiaWF0IjoxNzAzNzgyMjI5LCJleHAiOjE3MDM3ODU4Mjl9.nS19xXMou7EcXE2Zhi5TJI8CknJrbQws8O-fh0j8C60
Content-Type: application/json

{
  "productId":"658aa925fd3f251997ad8bae"
}